version: '2.2'
services:
  jenkins:
    image: crowdar/jenkinsbo:demoweb
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
    selenium_hub-mobile-apk:
      image: selenium/hub:3.14.0-curium
      ports:
        - 4444:4444
        samsung_s7_9.0:
            image: budtmo/docker-android-x86-9.0
            privileged: true
            # Increase scale number if needed
            scale: 1
            depends_on:
              - selenium_hub-mobile-apk
            ports:
              - 6080:6080
            # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
            volumes:
              - ${apkDirectory}:/root/tmp/sample_apk
              - ./video-samsung_s7_9:/tmp/video
            environment:
              - DEVICE=Samsung Galaxy S7
              - CONNECT_TO_GRID=true
              - APPIUM=true
              - SELENIUM_HOST=selenium_hub-mobile-apk
              - AUTO_RECORD=true
              nginx_web-sample:
                  image: nginx:stable
                  volumes:
                    - ./docker/jenkins_home/reportsVolume:/usr/share/nginx/html
                    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
                  ports:
                    - 8081:80
                  environment:
                    - TZ=America/Argentina/Buenos_Aires